# Required Vars:
# ${TARGET_NAME}

SET (SOLOUD_INSTALL_BINDIR bin)
IF(WIN32)
    SET(SOLOUD_INSTALL_LIBDIR bin)
    SET(SOLOUD_INSTALL_ARCHIVEDIR lib)
ELSE(WIN32)
    SET(SOLOUD_INSTALL_LIBDIR lib${LIB_POSTFIX})
    SET(SOLOUD_INSTALL_ARCHIVEDIR lib${LIB_POSTFIX})
ENDIF(WIN32)

SET (SOLOUD_PROJECT_NAME_LOWERCASE)
STRING (TOLOWER ${PROJECT_NAME} SOLOUD_PROJECT_NAME_LOWERCASE)
INSTALL (
	TARGETS ${TARGET_NAME}
	EXPORT ${SOLOUD_PROJECT_NAME_LOWERCASE}-config
	RUNTIME DESTINATION ${SOLOUD_INSTALL_BINDIR}
	BUNDLE  DESTINATION ${SOLOUD_INSTALL_BINDIR}
	LIBRARY DESTINATION ${SOLOUD_INSTALL_LIBDIR}
	ARCHIVE DESTINATION ${SOLOUD_INSTALL_ARCHIVEDIR}
)
